name: Build Docker Images for CI
# this workflow creates the Docker-Images used in the Continuous Integration (CI)
# It intentionally creates all images, such that they are on the same state

on:
  pull_request:
    paths:
    - 'scripts/docker_files/docker_file_ci_ubuntu_bionic/DockerFile'
    - '.github/workflows/build_docker_images_for_ci.yml'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file scripts/docker_files/docker_file_ci_ubuntu_bionic/DockerFile --tag kratosmultiphysics/kratos-image-ci-ubuntu-bionic
    - name: Docker Login
      uses: azure/docker-login@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Publish the Docker image
      run: docker push kratosmultiphysics/kratos-image-ci-ubuntu-bionic
