name: Build Docker Images for CI
# this workflow creates the Docker-Images used in the Continuous Integration (CI)
# It intentionally creates all images, such that they are on the same state

on:
  push:
    branches:
      - 'master'
    paths:
      - 'scripts/docker_files/docker_file_ci_ubuntu_22_04/*'
      - 'scripts/docker_files/docker_file_ci_centos_7/*'
      - '.github/workflows/build_docker_images_for_ci.yml'
  pull_request:
    branches:
      - 'master'
    paths:
      - 'scripts/docker_files/docker_file_ci_ubuntu_22_04/*'
      - 'scripts/docker_files/docker_file_ci_centos_7/*'
      - '.github/workflows/build_docker_images_for_ci.yml'

  workflow_dispatch:

# for cancelling redundant runs
concurrency:
  group: ci-${{ github.head_ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  build-docker-ubuntu-jammy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file scripts/docker_files/docker_file_ci_ubuntu_22_04/DockerFile --tag kratosmultiphysics/kratos-image-ci-ubuntu-22-04
    - name: Docker Login
      uses: azure/docker-login@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Publish the Docker image
      if: ${{ github.event_name == 'push'}}
      # only push the new image when the changes are merged to master
      run: docker push kratosmultiphysics/kratos-image-ci-ubuntu-22-04

  build-docker-rocky:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file scripts/docker_files/docker_file_ci_rockylinux8/DockerFile --tag kratosmultiphysics/kratos-image-ci-rocky8
    - name: Docker Login
      uses: azure/docker-login@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Publish the Docker image
      if: ${{ github.event_name == 'push'}}
      # only push the new image when the changes are merged to master
      run: docker push kratosmultiphysics/kratos-image-ci-rocky8
