name: CI

# this is required to satisfy the required checks ba replacing them with dummy checks
# see https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/defining-the-mergeability-of-pull-requests/troubleshooting-required-status-checks#handling-skipped-but-required-checks

on:
  pull_request:
    branches:
      - master
    paths:              # This must be the same as .github/workflows/ci.yml - "paths-ignore" !
      - '**.md'
      - 'documents/**'
      - 'scripts/**'

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        build-type: [Custom, FullDebug]
        compiler: [gcc, clang]
    steps:
    - run: 'echo "Dummy build, no checks executed ..."'

  windows:
    runs-on: windows-2022
    env:
      KRATOS_BUILD_TYPE: Custom

    steps:
    - run: 'echo "Dummy build, no checks executed ..."'
